/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facade;

import facade.banksystem.facade.BankFacade;

public class App {

    public static void main(String[] args) {
        BankFacade bankFacade = new BankFacade();
        bankFacade.createCustomer("Pedro", "3202334455", "pedro@gmail.com");
        System.out.println("transfer....");
        bankFacade.deposit(23000f);
        System.out.println("Customer information: " + bankFacade.getCustomerInformation());
        System.out.println("Account number: " + bankFacade.getAccountNumber());
        System.out.println("new balance: $" + bankFacade.getBalance());
        System.out.println("Withdraw....");
        bankFacade.withdraw(3000f);
        System.out.println("new balance " + bankFacade.getBalance());
    }
}
