/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interpreter;

import interpreter.context.Transaction;
import interpreter.interpreter.Interpreter;
import interpreter.interpreter.impl.MaxAmountInterpreter;
import interpreter.interpreter.impl.MinAmountInterpreter;
import interpreter.interpreter.validator.TransactionValidator;

public class App {

    public static void main(String[] args) {
        Interpreter maxAmountInterpreter = new MaxAmountInterpreter(10000);
        Interpreter minAmountInterpreter = new MinAmountInterpreter(10);

        TransactionValidator transactionValidator = new TransactionValidator();
        transactionValidator.addValidation(minAmountInterpreter);
        transactionValidator.addValidation(maxAmountInterpreter);

        Transaction transaction = new Transaction("12345", 100000);
        System.out.println("transaction is valid? " + (transactionValidator.interpret(transaction) ? "yes." : "no."));

    }
}
