/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package template_method;

import template_method.credit_card.concrete.Gold;
import template_method.credit_card.concrete.Silver;
import template_method.credit_card.template.CreditCard;

public class App {

    public static void main(String[] args) {
        CreditCard goldCreditCard = new Gold();
        CreditCard silverCreditCard = new Silver();
        goldCreditCard.generateHistoricData();
        silverCreditCard.generateHistoricData();
    }
}
