/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flyweight;

import flyweight.cachesystem.cache.CustomerCache;
import flyweight.cachesystem.model.Customer;

public class App {

    public static void main(String[] args) {
        CustomerCache cache = CustomerCache.getInstance();

        //searching first time
        Customer customerDb = cache.findById(1);
        System.out.println(customerDb.toString());

        //searching again
        Customer customerCache = cache.findById(1);
        System.out.println(customerCache.toString());

    }
}
