/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factory;

import factory.notificationsystem.Notification;
import factory.notificationsystem.factory.NotificationFactory;

public class App {

    public static void main(String[] args) {

        Notification email = NotificationFactory.getNotificationInstance("email");
        email.send();

        Notification sms = NotificationFactory.getNotificationInstance("sms");
        sms.send();

    }
}
