/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strategy;

import strategy.paymentmethod.context.Context;

public class App {

    public static void main(String[] args) {
        Context creditCardContext = new Context("CREDIT_CARD");
        creditCardContext.proccess(1200.0);
        Context paypalContext = new Context("PAYPAL");
        paypalContext.proccess(2300.0);
    }
}
