/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adapter;

import adapter.frauddetectionsystem.client.FraudDetectorClient;
import adapter.frauddetectionsystem.model.Transaction;
import adapter.frauddetectionsystem.service.FraudDetectionService;
import adapter.frauddetectionsystem.service.impl.FraudDetectionAdapter;

public class App {

    public static void main(String[] args) {
        Transaction transaction = new Transaction();
        FraudDetectorClient fraudDetectorClient = new FraudDetectorClient();
        FraudDetectionService fraudDetectionService = new FraudDetectionAdapter(fraudDetectorClient);
        transaction.setAmount(2000.0);
        transaction.setSenderAccount("12345");
        transaction.setRecipientAccount("6789");
        System.out.println(fraudDetectionService.isFraudulent(transaction));
    }
}
