/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package composite;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import composite.component.DocumentComponent;
import composite.impl.ParagraphComponent;
import composite.impl.SectionComponent;
import composite.impl.TableComponent;

import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws FileNotFoundException {

        DocumentComponent paragraph1 = new ParagraphComponent("first line.");
        DocumentComponent paragraph2 = new ParagraphComponent("second line.");
        DocumentComponent table = new TableComponent();

        SectionComponent section = new SectionComponent();
        section.addComponent(paragraph1);
        section.addComponent(paragraph2);
        section.addComponent(table);

        SectionComponent document = new SectionComponent();
        document.addComponent(section);

        PdfDocument pdfDocument = new PdfDocument(new PdfWriter("document.pdf"));
        Document pdf = new Document(pdfDocument);
        document.add(pdf);

        pdf.close();

    }
}
