/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxy;

import proxy.bankaccountcachesystem.model.impl.BankAccountImpl;
import proxy.bankaccountcachesystem.proxy.BankAccountProxy;

public class App {

    public static void main(String[] args) {
        BankAccountProxy proxy = new BankAccountProxy(1);
        BankAccountImpl bankAccount1 = proxy.getBankAccount();
        BankAccountImpl bankAccount2 = proxy.getBankAccount();
    }
}
