/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visitor;

import visitor.interestcalculator.calculator.InterestCalculator;
import visitor.interestcalculator.calculator.impl.PremiumInterestCalculator;
import visitor.interestcalculator.calculator.impl.RegularInterestCalculator;
import visitor.interestcalculator.customer.Customer;
import visitor.interestcalculator.customer.impl.Premium;
import visitor.interestcalculator.customer.impl.Regular;
import visitor.interestcalculator.visitable.Visitable;
import visitor.interestcalculator.visitable.impl.CreditCard;

public class App {

    public static void main(String[] args) {
        Customer premium = new Premium();
        Customer regular = new Regular();

        Visitable premiumCC = new CreditCard(premium);
        Visitable regularCC = new CreditCard(regular);

        InterestCalculator premiumIC = new PremiumInterestCalculator();
        InterestCalculator regularIC = new RegularInterestCalculator();

        premiumCC.accept(premiumIC);
        regularCC.accept(regularIC);
    }
}
