/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bridge;

import bridge.authsystem.impl.PasswordAuthenticationImpl;
import bridge.authsystem.interfaces.Authentication;
import bridge.authsystem.manager.AuthenticationManager;
import bridge.authsystem.manager.impl.PasswordAuthentication;

public class App {

    public static void main(String[] args) {
        Authentication passwordAuthImpl = new PasswordAuthenticationImpl();
        AuthenticationManager passwordAuth = new PasswordAuthentication(passwordAuthImpl);
        System.out.println(passwordAuth.authenticate() ? "Success." : "Fail.");
    }
}
