/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package state;

import state.account.Account;

public class App {

    public static void main(String[] args) {
        Account account = new Account();
        account.deposit(1000.0);
        account.withdraw(300.00);
        account.inactive();
        account.deposit(2000.0);
        account.withdraw(1000.00);
    }
}
