/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singleton;

public class App {

    public static void main(String[] args) {

        //get instance 1
        BankAccount bankAccount1 = BankAccount.getInstance();

        bankAccount1.deposit(200.0, "0967890");
        bankAccount1.withdraw(300.0, "023467");

        System.out.println("deposit instance1: " + bankAccount1.getDeposit());
        System.out.println("withdraw instance1: " + bankAccount1.getWithdraw());

        System.out.println("##########################");

        //get instance 2
        BankAccount bankAccount2 = BankAccount.getInstance();

        System.out.println("deposit instance2: " + bankAccount2.getDeposit());
        System.out.println("withdraw instance2: " + bankAccount2.getWithdraw());

    }
}
