/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mediator;

import mediator.customer.Customer;
import mediator.notification.NotificationMediator;

public class App {

    public static void main(String[] args) {

        NotificationMediator mediator = new NotificationMediator();

        Customer customer1 = new Customer(mediator);
        Customer customer2 = new Customer(mediator);

        mediator.addComunicator(customer1);
        mediator.addComunicator(customer2);

        customer1.sendMessage("Hi 1");
        customer2.sendMessage("Hi 2");

    }
}
