/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package observer;

import observer.account.Account;
import observer.observer.impl.Logger;
import observer.observer.impl.SMS;

public class App {
    public static void main(String[] args) {
        Account account = new Account();
        new Logger(account);
        new SMS(account);

        account.setBalance(1000.0);

    }
}
