/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package command;

import command.command.Command;
import command.command.impl.DepositCommand;
import command.command.impl.WithdrawCommand;
import command.model.Account;

public class App {

    public static void main(String[] args) {
        Account account = new Account("12345", 1200.0);
        Command depositCommand = new DepositCommand(account, 1000.0);
        depositCommand.execute();
        System.out.println("Balance after execute deposit command: " + depositCommand.getBalance());
        Command withdrawCommand = new WithdrawCommand(account, 2000.0);
        withdrawCommand.execute();
        System.out.println("Balance after execute withdraw command: " + withdrawCommand.getBalance());
    }
}
